<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>name</key>
  <string>GNU Linker Script</string>
  <key>scopeName</key>
  <string>source.linker</string>
  <key>fileTypes</key>
  <array>
    <string>x</string>
    <string>ld</string>
    <string>lds</string>
  </array>
  <key>patterns</key>
  <array>
    <dict><key>include</key><string>#comments</string></dict>
    <dict><key>include</key><string>#keywords</string></dict>
    <dict><key>include</key><string>#sections</string></dict>
    <dict><key>include</key><string>#numbers</string></dict>
    <dict><key>include</key><string>#strings</string></dict>
    <dict><key>include</key><string>#punctuation</string></dict>
    <dict><key>include</key><string>#identifiers</string></dict>
    <dict><key>include</key><string>#functions</string></dict>
  </array>
  <key>repository</key>
  <dict>
    <key>comments</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>#.*$</string>
          <key>name</key>
          <string>comment.line.number-sign.linker</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>/\*</string>
          <key>end</key>
          <string>\*/</string>
          <key>name</key>
          <string>comment.block.linker</string>
        </dict>
      </array>
    </dict>

    <key>keywords</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(ENTRY|PHDRS|SECTIONS|MEMORY|OUTPUT|OUTPUT_FORMAT|OUTPUT_ARCH|STARTUP|PROVIDE|INCLUDE|GROUP|SEARCH_DIR|KEEP|ASSERT|AT|ALIGN|SIZEOF|ADDR|LOADADDR|ORIGIN|LENGTH)\b</string>
          <key>name</key>
          <string>keyword.control.linker</string>
        </dict>
      </array>
    </dict>

    <key>sections</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\.\w+</string>
          <key>name</key>
          <string>entity.name.section.linker</string>
        </dict>
      </array>
    </dict>

    <key>numbers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b0x[0-9a-fA-F]+\b|\b\d+\b</string>
          <key>name</key>
          <string>constant.numeric.linker</string>
        </dict>
      </array>
    </dict>

    <key>strings</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>begin</key>
          <string>"</string>
          <key>end</key>
          <string>"</string>
          <key>name</key>
          <string>string.quoted.double.linker</string>
        </dict>
      </array>
    </dict>

    <key>punctuation</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>[:;{}()=*]</string>
          <key>name</key>
          <string>punctuation.separator.linker</string>
        </dict>
      </array>
    </dict>

    <key>identifiers</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b[_a-zA-Z][_a-zA-Z0-9]*\b</string>
          <key>name</key>
          <string>variable.other.linker</string>
        </dict>
      </array>
    </dict>

    <key>functions</key>
    <dict>
      <key>patterns</key>
      <array>
        <dict>
          <key>match</key>
          <string>\b(ABSOLUTE|DEFINED|ALIGN|MAX|MIN|SEGMENT_START|SIZEOF|ADDR|LOADADDR|BLOCK|NEXT|ASSERT)\b</string>
          <key>name</key>
          <string>support.function.linker</string>
        </dict>
      </array>
    </dict>
  </dict>
</dict>
</plist>
